### ISSUE TITLE
Profiling function calls

### ISSUE THREAD

**Issue by keichi** [SX-Aurora/nlcpy#2]
Is there an easy way to measure the runtime of every function call? I'm aware of `nlcpy.prof.ftrace_region` but I'd like to profile individual function calls rather than a region of code.

**Comment by dev-nlcpy** [comment]
The simple way is adding a function `nlcpy.request.set_offload_timing_onthefly()` at beggining of your code. After calling it, each NLCPy's function offloads a VE kernel immediately and waits until the kernel execution is finished. So, you can measure each function's runtime by using some profiling tools, for example, `cProfile` and `line_profiler`.

**Comment by keichi** [comment]
Thanks for your advise, it does work!
